#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# paradox theme
DEFAULT_USER="andrew"

# virtualenv aliases
# http://blog.doughellmann.com/2010/01/virtualenvwrapper-tips-and-tricks.html
alias v="workon"
alias v.deactivate="deactivate"
alias v.mk="mkvirtualenv --no-site-packages"
alias v.mk_withsitepackages="mkvirtualenv"
alias v.rm="rmvirtualenv"
alias v.switch="workon"
alias v.add2virtualenv="add2virtualenv"
alias v.cdsitepackages="cdsitepackages"
alias v.cd="cdvirtualenv"
alias v.ls="lsvirtualenv"
alias v.lssitepackages="lssitepackages"

# virtualenv
export VIRTUAL_ENV_DISABLE_PROMPT=true

# pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
pyenv virtualenvwrapper

# online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/helpfiles

# additional completions
fpath=(/usr/local/share/zsh/site-functions $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle :compinstall filename '/home/apope/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob notify
# End of lines configured by zsh-newuser-install
